# Generated by Django 5.1.6 on 2025-03-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homedetails',
            name='type',
            field=models.CharField(default='House', max_length=50),
        ),
    ]
