# Generated by Django 5.1.6 on 2025-03-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0002_homedetails_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='total_days',
            field=models.IntegerField(default=1),
        ),
    ]
