# Generated by Django 5.1.6 on 2025-03-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0003_rentdetails_total_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='pay_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
