# Generated by Django 5.1.6 on 2025-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlord', '0004_rentdetails_pay_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentdetails',
            name='payment_id',
            field=models.CharField(default='sampleid', max_length=200),
        ),
    ]
